// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#ifndef UI_CONEXION_BLUETOOTH_H
#define UI_CONEXION_BLUETOOTH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CONEXION_BLUETOOTH
extern void ui_CONEXION_BLUETOOTH_screen_init(void);
extern void ui_CONEXION_BLUETOOTH_screen_destroy(void);
extern lv_obj_t * ui_CONEXION_BLUETOOTH;
extern lv_obj_t * ui_CONEXION_BLUETOOTH1;
extern void ui_event_HOME2(lv_event_t * e);
extern lv_obj_t * ui_HOME2;
extern void ui_event_BLUETOOTH2(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTH2;
extern lv_obj_t * ui_BatteryBAR2;
extern lv_obj_t * ui_lblBatteryTxt2;
extern void ui_event_CANCELAR(lv_event_t * e);
extern lv_obj_t * ui_CANCELAR;
extern void ui_event_CONECTAR(lv_event_t * e);
extern lv_obj_t * ui_CONECTAR;
extern lv_obj_t * ui_BluetoothBAR2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

