// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#include "ui.h"

lv_obj_t * ui_CONEXION_BLUETOOTH = NULL;
lv_obj_t * ui_CONEXION_BLUETOOTH1 = NULL;
lv_obj_t * ui_HOME2 = NULL;
lv_obj_t * ui_BLUETOOTH2 = NULL;
lv_obj_t * ui_BatteryBAR2 = NULL;
lv_obj_t * ui_lblBatteryTxt2 = NULL;
lv_obj_t * ui_CANCELAR = NULL;
lv_obj_t * ui_CONECTAR = NULL;
lv_obj_t * ui_BluetoothBAR2 = NULL;
// event funtions
void ui_event_HOME2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

void ui_event_BLUETOOTH2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONEXION_BLUETOOTH, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_CONEXION_BLUETOOTH_screen_init);
    }
}

void ui_event_CANCELAR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

void ui_event_CONECTAR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SELECCION_DE_MODO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_SELECCION_DE_MODO_screen_init);
    }
}

// build funtions

void ui_CONEXION_BLUETOOTH_screen_init(void)
{
    ui_CONEXION_BLUETOOTH = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CONEXION_BLUETOOTH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CONEXION_BLUETOOTH1 = lv_img_create(ui_CONEXION_BLUETOOTH);
    lv_img_set_src(ui_CONEXION_BLUETOOTH1, &ui_img_2_png);
    lv_obj_set_width(ui_CONEXION_BLUETOOTH1, 480);
    lv_obj_set_height(ui_CONEXION_BLUETOOTH1, 320);
    lv_obj_set_align(ui_CONEXION_BLUETOOTH1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CONEXION_BLUETOOTH1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CONEXION_BLUETOOTH1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME2 = lv_btn_create(ui_CONEXION_BLUETOOTH);
    lv_obj_set_width(ui_HOME2, 40);
    lv_obj_set_height(ui_HOME2, 42);
    lv_obj_set_x(ui_HOME2, 216);
    lv_obj_set_y(ui_HOME2, -138);
    lv_obj_set_align(ui_HOME2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH2 = lv_btn_create(ui_CONEXION_BLUETOOTH);
    lv_obj_set_width(ui_BLUETOOTH2, 33);
    lv_obj_set_height(ui_BLUETOOTH2, 43);
    lv_obj_set_x(ui_BLUETOOTH2, 175);
    lv_obj_set_y(ui_BLUETOOTH2, -138);
    lv_obj_set_align(ui_BLUETOOTH2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLUETOOTH2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLUETOOTH2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBAR2 = lv_bar_create(ui_CONEXION_BLUETOOTH);
    lv_bar_set_value(ui_BatteryBAR2, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBAR2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBAR2, 50);
    lv_obj_set_height(ui_BatteryBAR2, 21);
    lv_obj_set_x(ui_BatteryBAR2, -199);
    lv_obj_set_y(ui_BatteryBAR2, -140);
    lv_obj_set_align(ui_BatteryBAR2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBAR2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteryBAR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBAR2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR2, lv_color_hex(0x5AEEFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblBatteryTxt2 = lv_label_create(ui_CONEXION_BLUETOOTH);
    lv_obj_set_width(ui_lblBatteryTxt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBatteryTxt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBatteryTxt2, -199);
    lv_obj_set_y(ui_lblBatteryTxt2, -140);
    lv_obj_set_align(ui_lblBatteryTxt2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblBatteryTxt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatteryTxt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatteryTxt2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatteryTxt2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatteryTxt2, lv_color_hex(0x54EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatteryTxt2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CANCELAR = lv_btn_create(ui_CONEXION_BLUETOOTH);
    lv_obj_set_width(ui_CANCELAR, 122);
    lv_obj_set_height(ui_CANCELAR, 32);
    lv_obj_set_x(ui_CANCELAR, -73);
    lv_obj_set_y(ui_CANCELAR, 132);
    lv_obj_set_align(ui_CANCELAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CANCELAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CANCELAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CANCELAR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CANCELAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CONECTAR = lv_btn_create(ui_CONEXION_BLUETOOTH);
    lv_obj_set_width(ui_CONECTAR, 122);
    lv_obj_set_height(ui_CONECTAR, 32);
    lv_obj_set_x(ui_CONECTAR, 66);
    lv_obj_set_y(ui_CONECTAR, 132);
    lv_obj_set_align(ui_CONECTAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CONECTAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CONECTAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CONECTAR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONECTAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BluetoothBAR2 = lv_bar_create(ui_CONEXION_BLUETOOTH);
    lv_obj_set_width(ui_BluetoothBAR2, 115);
    lv_obj_set_height(ui_BluetoothBAR2, 20);
    lv_obj_set_x(ui_BluetoothBAR2, 58);
    lv_obj_set_y(ui_BluetoothBAR2, 72);
    lv_obj_set_align(ui_BluetoothBAR2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BluetoothBAR2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BluetoothBAR2, lv_color_hex(0x002C6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluetoothBAR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BluetoothBAR2, lv_color_hex(0x22D4F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BluetoothBAR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BluetoothBAR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BluetoothBAR2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BluetoothBAR2, lv_color_hex(0x10F2FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluetoothBAR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HOME2, ui_event_HOME2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLUETOOTH2, ui_event_BLUETOOTH2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CANCELAR, ui_event_CANCELAR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CONECTAR, ui_event_CONECTAR, LV_EVENT_ALL, NULL);

}

void ui_CONEXION_BLUETOOTH_screen_destroy(void)
{
    if(ui_CONEXION_BLUETOOTH) lv_obj_del(ui_CONEXION_BLUETOOTH);

    // NULL screen variables
    ui_CONEXION_BLUETOOTH = NULL;
    ui_CONEXION_BLUETOOTH1 = NULL;
    ui_HOME2 = NULL;
    ui_BLUETOOTH2 = NULL;
    ui_BatteryBAR2 = NULL;
    ui_lblBatteryTxt2 = NULL;
    ui_CANCELAR = NULL;
    ui_CONECTAR = NULL;
    ui_BluetoothBAR2 = NULL;

}
