// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Palomita(lv_event_t * e);
void Tache(lv_event_t * e);
void Regresar(lv_event_t * e);
void MoveTurtleUP(lv_event_t * e);
void MoveTurtleDOWN(lv_event_t * e);
void TargetUP(lv_event_t * e);
void TargetDOWN(lv_event_t * e);
void PauseSession(lv_event_t * e);
void ContinueSession(lv_event_t * e);
void RepetirSession(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
