// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#include "ui.h"

/*
void Palomita(lv_event_t * e)
{
	// Your code here
}

void Tache(lv_event_t * e)
{
	// Your code here
}

void Regresar(lv_event_t * e)
{
	// Your code here
}

void MoveTurtleUP(lv_event_t * e)
{
	// Your code here
}

void MoveTurtleDOWN(lv_event_t * e)
{
	// Your code here
}

void TargetUP(lv_event_t * e)
{
	// Your code here
}

void TargetDOWN(lv_event_t * e)
{
	// Your code here
}

void PauseSession(lv_event_t * e)
{
	// Your code here
}

void ContinueSession(lv_event_t * e)
{
	// Your code here
}

void RepetirSession(lv_event_t * e)
{
	// Your code here
}
*/