// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#include "ui.h"

lv_obj_t * ui_INICIO = NULL;
lv_obj_t * ui_INICIO1 = NULL;
lv_obj_t * ui_HOME1 = NULL;
lv_obj_t * ui_BLUETOOTH1 = NULL;
lv_obj_t * ui_BatteryBAR1 = NULL;
lv_obj_t * ui_lblBatteryTxt1 = NULL;
lv_obj_t * ui_EMPEZAR = NULL;
// event funtions
void ui_event_HOME1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

void ui_event_BLUETOOTH1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONEXION_BLUETOOTH, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_CONEXION_BLUETOOTH_screen_init);
    }
}

void ui_event_EMPEZAR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONEXION_BLUETOOTH, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_CONEXION_BLUETOOTH_screen_init);
    }
}

// build funtions

void ui_INICIO_screen_init(void)
{
    ui_INICIO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_INICIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_INICIO1 = lv_img_create(ui_INICIO);
    lv_img_set_src(ui_INICIO1, &ui_img_1_png);
    lv_obj_set_width(ui_INICIO1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_INICIO1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_INICIO1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_INICIO1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_INICIO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME1 = lv_btn_create(ui_INICIO);
    lv_obj_set_width(ui_HOME1, 42);
    lv_obj_set_height(ui_HOME1, 45);
    lv_obj_set_x(ui_HOME1, 216);
    lv_obj_set_y(ui_HOME1, -138);
    lv_obj_set_align(ui_HOME1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH1 = lv_btn_create(ui_INICIO);
    lv_obj_set_width(ui_BLUETOOTH1, 29);
    lv_obj_set_height(ui_BLUETOOTH1, 41);
    lv_obj_set_x(ui_BLUETOOTH1, 174);
    lv_obj_set_y(ui_BLUETOOTH1, -138);
    lv_obj_set_align(ui_BLUETOOTH1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLUETOOTH1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLUETOOTH1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBAR1 = lv_bar_create(ui_INICIO);
    lv_bar_set_value(ui_BatteryBAR1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBAR1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBAR1, 51);
    lv_obj_set_height(ui_BatteryBAR1, 21);
    lv_obj_set_x(ui_BatteryBAR1, -199);
    lv_obj_set_y(ui_BatteryBAR1, -140);
    lv_obj_set_align(ui_BatteryBAR1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBAR1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteryBAR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBAR1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR1, lv_color_hex(0x5AEEFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblBatteryTxt1 = lv_label_create(ui_INICIO);
    lv_obj_set_width(ui_lblBatteryTxt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBatteryTxt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBatteryTxt1, -198);
    lv_obj_set_y(ui_lblBatteryTxt1, -140);
    lv_obj_set_align(ui_lblBatteryTxt1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblBatteryTxt1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatteryTxt1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatteryTxt1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatteryTxt1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatteryTxt1, lv_color_hex(0x54EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatteryTxt1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EMPEZAR = lv_btn_create(ui_INICIO);
    lv_obj_set_width(ui_EMPEZAR, 155);
    lv_obj_set_height(ui_EMPEZAR, 42);
    lv_obj_set_x(ui_EMPEZAR, 4);
    lv_obj_set_y(ui_EMPEZAR, 129);
    lv_obj_set_align(ui_EMPEZAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EMPEZAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EMPEZAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EMPEZAR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EMPEZAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HOME1, ui_event_HOME1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLUETOOTH1, ui_event_BLUETOOTH1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EMPEZAR, ui_event_EMPEZAR, LV_EVENT_ALL, NULL);

}

void ui_INICIO_screen_destroy(void)
{
    if(ui_INICIO) lv_obj_del(ui_INICIO);

    // NULL screen variables
    ui_INICIO = NULL;
    ui_INICIO1 = NULL;
    ui_HOME1 = NULL;
    ui_BLUETOOTH1 = NULL;
    ui_BatteryBAR1 = NULL;
    ui_lblBatteryTxt1 = NULL;
    ui_EMPEZAR = NULL;

}
