// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#ifndef UI_INICIO_H
#define UI_INICIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_INICIO
extern void ui_INICIO_screen_init(void);
extern void ui_INICIO_screen_destroy(void);
extern lv_obj_t * ui_INICIO;
extern lv_obj_t * ui_INICIO1;
extern void ui_event_HOME1(lv_event_t * e);
extern lv_obj_t * ui_HOME1;
extern void ui_event_BLUETOOTH1(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTH1;
extern lv_obj_t * ui_BatteryBAR1;
extern lv_obj_t * ui_lblBatteryTxt1;
extern void ui_event_EMPEZAR(lv_event_t * e);
extern lv_obj_t * ui_EMPEZAR;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

