// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#include "ui.h"

lv_obj_t * ui_MODO_JUEGO = NULL;
lv_obj_t * ui_MODO_JUEGO1 = NULL;
lv_obj_t * ui_HOME4 = NULL;
lv_obj_t * ui_BLUETOOTH4 = NULL;
lv_obj_t * ui_BACK4 = NULL;
lv_obj_t * ui_BatteryBAR4 = NULL;
lv_obj_t * ui_lblBatteryTxt4 = NULL;
lv_obj_t * ui_lblCOLOR4 = NULL;
lv_obj_t * ui_lblPOINT4 = NULL;
lv_obj_t * ui_PALOMITA = NULL;
lv_obj_t * ui_TACHE = NULL;
lv_obj_t * ui_REGRESAR = NULL;
lv_obj_t * ui_TERMINAR4 = NULL;
lv_obj_t * ui_MoveTurtleUP4 = NULL;
lv_obj_t * ui_MoveTurtleDOWN4 = NULL;
// event funtions
void ui_event_HOME4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

void ui_event_BLUETOOTH4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONEXION_BLUETOOTH, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_CONEXION_BLUETOOTH_screen_init);
    }
}

void ui_event_BACK4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SELECCION_DE_MODO, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SELECCION_DE_MODO_screen_init);
    }
}

void ui_event_PALOMITA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Palomita(e);
    }
}

void ui_event_TACHE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Tache(e);
    }
}

void ui_event_REGRESAR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Regresar(e);
    }
}

void ui_event_TERMINAR4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RESUMEN_DE_SESSION, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_RESUMEN_DE_SESSION_screen_init);
    }
}

void ui_event_MoveTurtleUP4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        MoveTurtleUP(e);
    }
}

void ui_event_MoveTurtleDOWN4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        MoveTurtleDOWN(e);
    }
}

// build funtions

void ui_MODO_JUEGO_screen_init(void)
{
    ui_MODO_JUEGO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MODO_JUEGO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MODO_JUEGO1 = lv_img_create(ui_MODO_JUEGO);
    lv_img_set_src(ui_MODO_JUEGO1, &ui_img_4_png);
    lv_obj_set_width(ui_MODO_JUEGO1, 480);
    lv_obj_set_height(ui_MODO_JUEGO1, 320);
    lv_obj_set_align(ui_MODO_JUEGO1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MODO_JUEGO1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MODO_JUEGO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME4 = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_HOME4, 41);
    lv_obj_set_height(ui_HOME4, 41);
    lv_obj_set_x(ui_HOME4, 217);
    lv_obj_set_y(ui_HOME4, -139);
    lv_obj_set_align(ui_HOME4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH4 = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_BLUETOOTH4, 21);
    lv_obj_set_height(ui_BLUETOOTH4, 39);
    lv_obj_set_x(ui_BLUETOOTH4, 180);
    lv_obj_set_y(ui_BLUETOOTH4, -138);
    lv_obj_set_align(ui_BLUETOOTH4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLUETOOTH4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLUETOOTH4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK4 = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_BACK4, 35);
    lv_obj_set_height(ui_BACK4, 44);
    lv_obj_set_x(ui_BACK4, 146);
    lv_obj_set_y(ui_BACK4, -138);
    lv_obj_set_align(ui_BACK4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACK4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACK4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBAR4 = lv_bar_create(ui_MODO_JUEGO);
    lv_bar_set_value(ui_BatteryBAR4, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBAR4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBAR4, 51);
    lv_obj_set_height(ui_BatteryBAR4, 21);
    lv_obj_set_x(ui_BatteryBAR4, -199);
    lv_obj_set_y(ui_BatteryBAR4, -141);
    lv_obj_set_align(ui_BatteryBAR4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBAR4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteryBAR4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBAR4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR4, lv_color_hex(0x5AEEFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblBatteryTxt4 = lv_label_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_lblBatteryTxt4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBatteryTxt4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBatteryTxt4, -199);
    lv_obj_set_y(ui_lblBatteryTxt4, -140);
    lv_obj_set_align(ui_lblBatteryTxt4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblBatteryTxt4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatteryTxt4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatteryTxt4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatteryTxt4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatteryTxt4, lv_color_hex(0x54EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatteryTxt4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCOLOR4 = lv_label_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_lblCOLOR4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCOLOR4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCOLOR4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblCOLOR4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCOLOR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblCOLOR4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCOLOR4, &ui_font_Noto_San_Kr, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPOINT4 = lv_label_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_lblPOINT4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPOINT4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPOINT4, 200);
    lv_obj_set_y(ui_lblPOINT4, -77);
    lv_obj_set_align(ui_lblPOINT4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblPOINT4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPOINT4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblPOINT4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPOINT4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PALOMITA = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_PALOMITA, 38);
    lv_obj_set_height(ui_PALOMITA, 38);
    lv_obj_set_x(ui_PALOMITA, -25);
    lv_obj_set_y(ui_PALOMITA, 115);
    lv_obj_set_align(ui_PALOMITA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PALOMITA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PALOMITA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PALOMITA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PALOMITA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TACHE = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_TACHE, 38);
    lv_obj_set_height(ui_TACHE, 38);
    lv_obj_set_x(ui_TACHE, 26);
    lv_obj_set_y(ui_TACHE, 115);
    lv_obj_set_align(ui_TACHE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TACHE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TACHE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TACHE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TACHE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_REGRESAR = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_REGRESAR, 116);
    lv_obj_set_height(ui_REGRESAR, 28);
    lv_obj_set_x(ui_REGRESAR, 153);
    lv_obj_set_y(ui_REGRESAR, 73);
    lv_obj_set_align(ui_REGRESAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_REGRESAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_REGRESAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_REGRESAR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_REGRESAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TERMINAR4 = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_TERMINAR4, 116);
    lv_obj_set_height(ui_TERMINAR4, 28);
    lv_obj_set_x(ui_TERMINAR4, 153);
    lv_obj_set_y(ui_TERMINAR4, 116);
    lv_obj_set_align(ui_TERMINAR4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TERMINAR4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TERMINAR4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TERMINAR4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TERMINAR4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveTurtleUP4 = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_MoveTurtleUP4, 40);
    lv_obj_set_height(ui_MoveTurtleUP4, 34);
    lv_obj_set_x(ui_MoveTurtleUP4, 195);
    lv_obj_set_y(ui_MoveTurtleUP4, -22);
    lv_obj_set_align(ui_MoveTurtleUP4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveTurtleUP4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoveTurtleUP4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoveTurtleUP4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoveTurtleUP4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveTurtleDOWN4 = lv_btn_create(ui_MODO_JUEGO);
    lv_obj_set_width(ui_MoveTurtleDOWN4, 40);
    lv_obj_set_height(ui_MoveTurtleDOWN4, 34);
    lv_obj_set_x(ui_MoveTurtleDOWN4, 195);
    lv_obj_set_y(ui_MoveTurtleDOWN4, 22);
    lv_obj_set_align(ui_MoveTurtleDOWN4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveTurtleDOWN4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoveTurtleDOWN4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoveTurtleDOWN4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoveTurtleDOWN4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HOME4, ui_event_HOME4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLUETOOTH4, ui_event_BLUETOOTH4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK4, ui_event_BACK4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PALOMITA, ui_event_PALOMITA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TACHE, ui_event_TACHE, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_REGRESAR, ui_event_REGRESAR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TERMINAR4, ui_event_TERMINAR4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoveTurtleUP4, ui_event_MoveTurtleUP4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoveTurtleDOWN4, ui_event_MoveTurtleDOWN4, LV_EVENT_ALL, NULL);

}

void ui_MODO_JUEGO_screen_destroy(void)
{
    if(ui_MODO_JUEGO) lv_obj_del(ui_MODO_JUEGO);

    // NULL screen variables
    ui_MODO_JUEGO = NULL;
    ui_MODO_JUEGO1 = NULL;
    ui_HOME4 = NULL;
    ui_BLUETOOTH4 = NULL;
    ui_BACK4 = NULL;
    ui_BatteryBAR4 = NULL;
    ui_lblBatteryTxt4 = NULL;
    ui_lblCOLOR4 = NULL;
    ui_lblPOINT4 = NULL;
    ui_PALOMITA = NULL;
    ui_TACHE = NULL;
    ui_REGRESAR = NULL;
    ui_TERMINAR4 = NULL;
    ui_MoveTurtleUP4 = NULL;
    ui_MoveTurtleDOWN4 = NULL;

}
