// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#include "ui.h"

lv_obj_t * ui_MODO_REHABILITACION = NULL;
lv_obj_t * ui_MODO_REHABILITACION1 = NULL;
lv_obj_t * ui_HOME5 = NULL;
lv_obj_t * ui_BLUETOOTH5 = NULL;
lv_obj_t * ui_BACK5 = NULL;
lv_obj_t * ui_BatteryBAR5 = NULL;
lv_obj_t * ui_lblBatteryTxt5 = NULL;
lv_obj_t * ui_lblTargetSET = NULL;
lv_obj_t * ui_TargetUP = NULL;
lv_obj_t * ui_TargetDOWN = NULL;
lv_obj_t * ui_lblCurrentCOUNT = NULL;
lv_obj_t * ui_lblTargetCOUNT = NULL;
lv_obj_t * ui_ProgressBAR = NULL;
lv_obj_t * ui_lblProgressPERCENT = NULL;
lv_obj_t * ui_PAUSAR = NULL;
lv_obj_t * ui_CONTINUAR = NULL;
lv_obj_t * ui_TERMINAR5 = NULL;
lv_obj_t * ui_MoveTurtleUP5 = NULL;
lv_obj_t * ui_MoveTurtleDOWN5 = NULL;
// event funtions
void ui_event_HOME5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

void ui_event_BLUETOOTH5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONEXION_BLUETOOTH, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_CONEXION_BLUETOOTH_screen_init);
    }
}

void ui_event_BACK5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SELECCION_DE_MODO, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SELECCION_DE_MODO_screen_init);
    }
}

void ui_event_TargetUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        TargetUP(e);
    }
}

void ui_event_TargetDOWN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        TargetDOWN(e);
    }
}

void ui_event_PAUSAR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PauseSession(e);
    }
}

void ui_event_CONTINUAR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ContinueSession(e);
    }
}

void ui_event_TERMINAR5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RESUMEN_DE_SESSION, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_RESUMEN_DE_SESSION_screen_init);
    }
}

void ui_event_MoveTurtleUP5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        MoveTurtleUP(e);
    }
}

void ui_event_MoveTurtleDOWN5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        MoveTurtleDOWN(e);
    }
}

// build funtions

void ui_MODO_REHABILITACION_screen_init(void)
{
    ui_MODO_REHABILITACION = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MODO_REHABILITACION, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MODO_REHABILITACION1 = lv_img_create(ui_MODO_REHABILITACION);
    lv_img_set_src(ui_MODO_REHABILITACION1, &ui_img_5_png);
    lv_obj_set_width(ui_MODO_REHABILITACION1, 480);
    lv_obj_set_height(ui_MODO_REHABILITACION1, 320);
    lv_obj_set_align(ui_MODO_REHABILITACION1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MODO_REHABILITACION1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MODO_REHABILITACION1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME5 = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_HOME5, 44);
    lv_obj_set_height(ui_HOME5, 42);
    lv_obj_set_x(ui_HOME5, 216);
    lv_obj_set_y(ui_HOME5, -137);
    lv_obj_set_align(ui_HOME5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH5 = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_BLUETOOTH5, 21);
    lv_obj_set_height(ui_BLUETOOTH5, 41);
    lv_obj_set_x(ui_BLUETOOTH5, 180);
    lv_obj_set_y(ui_BLUETOOTH5, -138);
    lv_obj_set_align(ui_BLUETOOTH5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLUETOOTH5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLUETOOTH5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK5 = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_BACK5, 35);
    lv_obj_set_height(ui_BACK5, 44);
    lv_obj_set_x(ui_BACK5, 147);
    lv_obj_set_y(ui_BACK5, -138);
    lv_obj_set_align(ui_BACK5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACK5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACK5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACK5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBAR5 = lv_bar_create(ui_MODO_REHABILITACION);
    lv_bar_set_value(ui_BatteryBAR5, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBAR5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBAR5, 50);
    lv_obj_set_height(ui_BatteryBAR5, 21);
    lv_obj_set_x(ui_BatteryBAR5, -199);
    lv_obj_set_y(ui_BatteryBAR5, -140);
    lv_obj_set_align(ui_BatteryBAR5, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBAR5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteryBAR5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBAR5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR5, lv_color_hex(0x5AEEFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblBatteryTxt5 = lv_label_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_lblBatteryTxt5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBatteryTxt5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBatteryTxt5, -199);
    lv_obj_set_y(ui_lblBatteryTxt5, -140);
    lv_obj_set_align(ui_lblBatteryTxt5, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblBatteryTxt5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatteryTxt5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatteryTxt5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatteryTxt5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatteryTxt5, lv_color_hex(0x54EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatteryTxt5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTargetSET = lv_label_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_lblTargetSET, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTargetSET, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTargetSET, -98);
    lv_obj_set_y(ui_lblTargetSET, -55);
    lv_obj_set_align(ui_lblTargetSET, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblTargetSET, lv_color_hex(0xB3D4E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTargetSET, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTargetSET, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTargetSET, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetUP = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_TargetUP, 42);
    lv_obj_set_height(ui_TargetUP, 35);
    lv_obj_set_x(ui_TargetUP, -44);
    lv_obj_set_y(ui_TargetUP, -75);
    lv_obj_set_align(ui_TargetUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TargetUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TargetUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TargetUP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TargetUP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetDOWN = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_TargetDOWN, 42);
    lv_obj_set_height(ui_TargetDOWN, 35);
    lv_obj_set_x(ui_TargetDOWN, -44);
    lv_obj_set_y(ui_TargetDOWN, -35);
    lv_obj_set_align(ui_TargetDOWN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TargetDOWN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TargetDOWN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TargetDOWN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TargetDOWN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCurrentCOUNT = lv_label_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_lblCurrentCOUNT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCurrentCOUNT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCurrentCOUNT, 70);
    lv_obj_set_y(ui_lblCurrentCOUNT, -61);
    lv_obj_set_align(ui_lblCurrentCOUNT, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblCurrentCOUNT, lv_color_hex(0xB3D4E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCurrentCOUNT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblCurrentCOUNT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCurrentCOUNT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTargetCOUNT = lv_label_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_lblTargetCOUNT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTargetCOUNT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTargetCOUNT, 134);
    lv_obj_set_y(ui_lblTargetCOUNT, -61);
    lv_obj_set_align(ui_lblTargetCOUNT, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblTargetCOUNT, lv_color_hex(0xB3D4E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTargetCOUNT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTargetCOUNT, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTargetCOUNT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgressBAR = lv_bar_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_ProgressBAR, 84);
    lv_obj_set_height(ui_ProgressBAR, 16);
    lv_obj_set_x(ui_ProgressBAR, 86);
    lv_obj_set_y(ui_ProgressBAR, -37);
    lv_obj_set_align(ui_ProgressBAR, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ProgressBAR, lv_color_hex(0x002052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgressBAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ProgressBAR, lv_color_hex(0xA9EDF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ProgressBAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ProgressBAR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ProgressBAR, lv_color_hex(0x10F2FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgressBAR, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblProgressPERCENT = lv_label_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_lblProgressPERCENT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProgressPERCENT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProgressPERCENT, 152);
    lv_obj_set_y(ui_lblProgressPERCENT, -37);
    lv_obj_set_align(ui_lblProgressPERCENT, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblProgressPERCENT, lv_color_hex(0xB3D4E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProgressPERCENT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProgressPERCENT, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProgressPERCENT, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PAUSAR = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_PAUSAR, 90);
    lv_obj_set_height(ui_PAUSAR, 50);
    lv_obj_set_x(ui_PAUSAR, -106);
    lv_obj_set_y(ui_PAUSAR, 124);
    lv_obj_set_align(ui_PAUSAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PAUSAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PAUSAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PAUSAR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PAUSAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CONTINUAR = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_CONTINUAR, 100);
    lv_obj_set_height(ui_CONTINUAR, 50);
    lv_obj_set_x(ui_CONTINUAR, 6);
    lv_obj_set_y(ui_CONTINUAR, 124);
    lv_obj_set_align(ui_CONTINUAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CONTINUAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CONTINUAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CONTINUAR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONTINUAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TERMINAR5 = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_TERMINAR5, 90);
    lv_obj_set_height(ui_TERMINAR5, 50);
    lv_obj_set_x(ui_TERMINAR5, 117);
    lv_obj_set_y(ui_TERMINAR5, 124);
    lv_obj_set_align(ui_TERMINAR5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TERMINAR5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TERMINAR5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TERMINAR5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TERMINAR5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveTurtleUP5 = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_MoveTurtleUP5, 40);
    lv_obj_set_height(ui_MoveTurtleUP5, 34);
    lv_obj_set_x(ui_MoveTurtleUP5, 163);
    lv_obj_set_y(ui_MoveTurtleUP5, 5);
    lv_obj_set_align(ui_MoveTurtleUP5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveTurtleUP5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoveTurtleUP5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoveTurtleUP5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoveTurtleUP5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveTurtleDOWN5 = lv_btn_create(ui_MODO_REHABILITACION);
    lv_obj_set_width(ui_MoveTurtleDOWN5, 40);
    lv_obj_set_height(ui_MoveTurtleDOWN5, 34);
    lv_obj_set_x(ui_MoveTurtleDOWN5, 163);
    lv_obj_set_y(ui_MoveTurtleDOWN5, 50);
    lv_obj_set_align(ui_MoveTurtleDOWN5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveTurtleDOWN5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoveTurtleDOWN5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoveTurtleDOWN5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoveTurtleDOWN5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HOME5, ui_event_HOME5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLUETOOTH5, ui_event_BLUETOOTH5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK5, ui_event_BACK5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TargetUP, ui_event_TargetUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TargetDOWN, ui_event_TargetDOWN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PAUSAR, ui_event_PAUSAR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CONTINUAR, ui_event_CONTINUAR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TERMINAR5, ui_event_TERMINAR5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoveTurtleUP5, ui_event_MoveTurtleUP5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoveTurtleDOWN5, ui_event_MoveTurtleDOWN5, LV_EVENT_ALL, NULL);

}

void ui_MODO_REHABILITACION_screen_destroy(void)
{
    if(ui_MODO_REHABILITACION) lv_obj_del(ui_MODO_REHABILITACION);

    // NULL screen variables
    ui_MODO_REHABILITACION = NULL;
    ui_MODO_REHABILITACION1 = NULL;
    ui_HOME5 = NULL;
    ui_BLUETOOTH5 = NULL;
    ui_BACK5 = NULL;
    ui_BatteryBAR5 = NULL;
    ui_lblBatteryTxt5 = NULL;
    ui_lblTargetSET = NULL;
    ui_TargetUP = NULL;
    ui_TargetDOWN = NULL;
    ui_lblCurrentCOUNT = NULL;
    ui_lblTargetCOUNT = NULL;
    ui_ProgressBAR = NULL;
    ui_lblProgressPERCENT = NULL;
    ui_PAUSAR = NULL;
    ui_CONTINUAR = NULL;
    ui_TERMINAR5 = NULL;
    ui_MoveTurtleUP5 = NULL;
    ui_MoveTurtleDOWN5 = NULL;

}
