// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#ifndef UI_MODO_REHABILITACION_H
#define UI_MODO_REHABILITACION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MODO_REHABILITACION
extern void ui_MODO_REHABILITACION_screen_init(void);
extern void ui_MODO_REHABILITACION_screen_destroy(void);
extern lv_obj_t * ui_MODO_REHABILITACION;
extern lv_obj_t * ui_MODO_REHABILITACION1;
extern void ui_event_HOME5(lv_event_t * e);
extern lv_obj_t * ui_HOME5;
extern void ui_event_BLUETOOTH5(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTH5;
extern void ui_event_BACK5(lv_event_t * e);
extern lv_obj_t * ui_BACK5;
extern lv_obj_t * ui_BatteryBAR5;
extern lv_obj_t * ui_lblBatteryTxt5;
extern lv_obj_t * ui_lblTargetSET;
extern void ui_event_TargetUP(lv_event_t * e);
extern lv_obj_t * ui_TargetUP;
extern void ui_event_TargetDOWN(lv_event_t * e);
extern lv_obj_t * ui_TargetDOWN;
extern lv_obj_t * ui_lblCurrentCOUNT;
extern lv_obj_t * ui_lblTargetCOUNT;
extern lv_obj_t * ui_ProgressBAR;
extern lv_obj_t * ui_lblProgressPERCENT;
extern void ui_event_PAUSAR(lv_event_t * e);
extern lv_obj_t * ui_PAUSAR;
extern void ui_event_CONTINUAR(lv_event_t * e);
extern lv_obj_t * ui_CONTINUAR;
extern void ui_event_TERMINAR5(lv_event_t * e);
extern lv_obj_t * ui_TERMINAR5;
extern void ui_event_MoveTurtleUP5(lv_event_t * e);
extern lv_obj_t * ui_MoveTurtleUP5;
extern void ui_event_MoveTurtleDOWN5(lv_event_t * e);
extern lv_obj_t * ui_MoveTurtleDOWN5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

