// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#ifndef UI_MODO_JUEGO_H
#define UI_MODO_JUEGO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MODO_JUEGO
extern void ui_MODO_JUEGO_screen_init(void);
extern void ui_MODO_JUEGO_screen_destroy(void);
extern lv_obj_t * ui_MODO_JUEGO;
extern lv_obj_t * ui_MODO_JUEGO1;
extern void ui_event_HOME4(lv_event_t * e);
extern lv_obj_t * ui_HOME4;
extern void ui_event_BLUETOOTH4(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTH4;
extern void ui_event_BACK4(lv_event_t * e);
extern lv_obj_t * ui_BACK4;
extern lv_obj_t * ui_BatteryBAR4;
extern lv_obj_t * ui_lblBatteryTxt4;
extern lv_obj_t * ui_lblCOLOR4;
extern lv_obj_t * ui_lblPOINT4;
extern void ui_event_PALOMITA(lv_event_t * e);
extern lv_obj_t * ui_PALOMITA;
extern void ui_event_TACHE(lv_event_t * e);
extern lv_obj_t * ui_TACHE;
extern void ui_event_REGRESAR(lv_event_t * e);
extern lv_obj_t * ui_REGRESAR;
extern void ui_event_TERMINAR4(lv_event_t * e);
extern lv_obj_t * ui_TERMINAR4;
extern void ui_event_MoveTurtleUP4(lv_event_t * e);
extern lv_obj_t * ui_MoveTurtleUP4;
extern void ui_event_MoveTurtleDOWN4(lv_event_t * e);
extern lv_obj_t * ui_MoveTurtleDOWN4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

