// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#ifndef UI_RESUMEN_DE_SESSION_H
#define UI_RESUMEN_DE_SESSION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RESUMEN_DE_SESSION
extern void ui_RESUMEN_DE_SESSION_screen_init(void);
extern void ui_RESUMEN_DE_SESSION_screen_destroy(void);
extern lv_obj_t * ui_RESUMEN_DE_SESSION;
extern lv_obj_t * ui_RESUMEN_DE_SESSION1;
extern void ui_event_HOME6(lv_event_t * e);
extern lv_obj_t * ui_HOME6;
extern void ui_event_BLUETOOTH6(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTH6;
extern lv_obj_t * ui_BatteryBAR6;
extern lv_obj_t * ui_lblBatteryTxt6;
extern lv_obj_t * ui_lblSummaryTarget;
extern lv_obj_t * ui_lblSummaryAchieved;
extern void ui_event_REPETIR(lv_event_t * e);
extern lv_obj_t * ui_REPETIR;
extern void ui_event_INICIO6(lv_event_t * e);
extern lv_obj_t * ui_INICIO6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

