// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#include "ui.h"

lv_obj_t * ui_RESUMEN_DE_SESSION = NULL;
lv_obj_t * ui_RESUMEN_DE_SESSION1 = NULL;
lv_obj_t * ui_HOME6 = NULL;
lv_obj_t * ui_BLUETOOTH6 = NULL;
lv_obj_t * ui_BatteryBAR6 = NULL;
lv_obj_t * ui_lblBatteryTxt6 = NULL;
lv_obj_t * ui_lblSummaryTarget = NULL;
lv_obj_t * ui_lblSummaryAchieved = NULL;
lv_obj_t * ui_REPETIR = NULL;
lv_obj_t * ui_INICIO6 = NULL;
// event funtions
void ui_event_HOME6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

void ui_event_BLUETOOTH6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONEXION_BLUETOOTH, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_CONEXION_BLUETOOTH_screen_init);
    }
}

void ui_event_REPETIR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        RepetirSession(e);
    }
}

void ui_event_INICIO6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

// build funtions

void ui_RESUMEN_DE_SESSION_screen_init(void)
{
    ui_RESUMEN_DE_SESSION = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RESUMEN_DE_SESSION, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RESUMEN_DE_SESSION1 = lv_img_create(ui_RESUMEN_DE_SESSION);
    lv_img_set_src(ui_RESUMEN_DE_SESSION1, &ui_img_6_png);
    lv_obj_set_width(ui_RESUMEN_DE_SESSION1, 480);
    lv_obj_set_height(ui_RESUMEN_DE_SESSION1, 320);
    lv_obj_set_align(ui_RESUMEN_DE_SESSION1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RESUMEN_DE_SESSION1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RESUMEN_DE_SESSION1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME6 = lv_btn_create(ui_RESUMEN_DE_SESSION);
    lv_obj_set_width(ui_HOME6, 41);
    lv_obj_set_height(ui_HOME6, 41);
    lv_obj_set_x(ui_HOME6, 216);
    lv_obj_set_y(ui_HOME6, -137);
    lv_obj_set_align(ui_HOME6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH6 = lv_btn_create(ui_RESUMEN_DE_SESSION);
    lv_obj_set_width(ui_BLUETOOTH6, 32);
    lv_obj_set_height(ui_BLUETOOTH6, 40);
    lv_obj_set_x(ui_BLUETOOTH6, 174);
    lv_obj_set_y(ui_BLUETOOTH6, -137);
    lv_obj_set_align(ui_BLUETOOTH6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLUETOOTH6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLUETOOTH6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBAR6 = lv_bar_create(ui_RESUMEN_DE_SESSION);
    lv_bar_set_value(ui_BatteryBAR6, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBAR6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBAR6, 50);
    lv_obj_set_height(ui_BatteryBAR6, 21);
    lv_obj_set_x(ui_BatteryBAR6, -199);
    lv_obj_set_y(ui_BatteryBAR6, -140);
    lv_obj_set_align(ui_BatteryBAR6, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBAR6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteryBAR6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBAR6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR6, lv_color_hex(0x5AEEFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblBatteryTxt6 = lv_label_create(ui_RESUMEN_DE_SESSION);
    lv_obj_set_width(ui_lblBatteryTxt6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBatteryTxt6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBatteryTxt6, -198);
    lv_obj_set_y(ui_lblBatteryTxt6, -140);
    lv_obj_set_align(ui_lblBatteryTxt6, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblBatteryTxt6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatteryTxt6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatteryTxt6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatteryTxt6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatteryTxt6, lv_color_hex(0x54EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatteryTxt6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSummaryTarget = lv_label_create(ui_RESUMEN_DE_SESSION);
    lv_obj_set_width(ui_lblSummaryTarget, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSummaryTarget, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSummaryTarget, -28);
    lv_obj_set_y(ui_lblSummaryTarget, 47);
    lv_obj_set_align(ui_lblSummaryTarget, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblSummaryTarget, lv_color_hex(0x43F2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSummaryTarget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSummaryTarget, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSummaryTarget, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSummaryAchieved = lv_label_create(ui_RESUMEN_DE_SESSION);
    lv_obj_set_width(ui_lblSummaryAchieved, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSummaryAchieved, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSummaryAchieved, 116);
    lv_obj_set_y(ui_lblSummaryAchieved, 47);
    lv_obj_set_align(ui_lblSummaryAchieved, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblSummaryAchieved, lv_color_hex(0x43F2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSummaryAchieved, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSummaryAchieved, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSummaryAchieved, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_REPETIR = lv_btn_create(ui_RESUMEN_DE_SESSION);
    lv_obj_set_width(ui_REPETIR, 109);
    lv_obj_set_height(ui_REPETIR, 36);
    lv_obj_set_x(ui_REPETIR, -66);
    lv_obj_set_y(ui_REPETIR, 126);
    lv_obj_set_align(ui_REPETIR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_REPETIR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_REPETIR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_REPETIR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_REPETIR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_INICIO6 = lv_btn_create(ui_RESUMEN_DE_SESSION);
    lv_obj_set_width(ui_INICIO6, 120);
    lv_obj_set_height(ui_INICIO6, 36);
    lv_obj_set_x(ui_INICIO6, 72);
    lv_obj_set_y(ui_INICIO6, 126);
    lv_obj_set_align(ui_INICIO6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_INICIO6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_INICIO6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_INICIO6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_INICIO6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HOME6, ui_event_HOME6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLUETOOTH6, ui_event_BLUETOOTH6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_REPETIR, ui_event_REPETIR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_INICIO6, ui_event_INICIO6, LV_EVENT_ALL, NULL);

}

void ui_RESUMEN_DE_SESSION_screen_destroy(void)
{
    if(ui_RESUMEN_DE_SESSION) lv_obj_del(ui_RESUMEN_DE_SESSION);

    // NULL screen variables
    ui_RESUMEN_DE_SESSION = NULL;
    ui_RESUMEN_DE_SESSION1 = NULL;
    ui_HOME6 = NULL;
    ui_BLUETOOTH6 = NULL;
    ui_BatteryBAR6 = NULL;
    ui_lblBatteryTxt6 = NULL;
    ui_lblSummaryTarget = NULL;
    ui_lblSummaryAchieved = NULL;
    ui_REPETIR = NULL;
    ui_INICIO6 = NULL;

}
