// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#ifndef UI_SELECCION_DE_MODO_H
#define UI_SELECCION_DE_MODO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SELECCION_DE_MODO
extern void ui_SELECCION_DE_MODO_screen_init(void);
extern void ui_SELECCION_DE_MODO_screen_destroy(void);
extern lv_obj_t * ui_SELECCION_DE_MODO;
extern lv_obj_t * ui_SELECCION_DE_MODO1;
extern void ui_event_HOME3(lv_event_t * e);
extern lv_obj_t * ui_HOME3;
extern void ui_event_BLUETOOTH3(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTH3;
extern lv_obj_t * ui_BatteryBAR3;
extern lv_obj_t * ui_lblBatteryTxt3;
extern void ui_event_ModoJUEGO(lv_event_t * e);
extern lv_obj_t * ui_ModoJUEGO;
extern void ui_event_ModoREHABILITACION(lv_event_t * e);
extern lv_obj_t * ui_ModoREHABILITACION;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

