// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Ballena_Screen

#include "ui.h"

lv_obj_t * ui_SELECCION_DE_MODO = NULL;
lv_obj_t * ui_SELECCION_DE_MODO1 = NULL;
lv_obj_t * ui_HOME3 = NULL;
lv_obj_t * ui_BLUETOOTH3 = NULL;
lv_obj_t * ui_BatteryBAR3 = NULL;
lv_obj_t * ui_lblBatteryTxt3 = NULL;
lv_obj_t * ui_ModoJUEGO = NULL;
lv_obj_t * ui_ModoREHABILITACION = NULL;
// event funtions
void ui_event_HOME3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_INICIO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_INICIO_screen_init);
    }
}

void ui_event_BLUETOOTH3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONEXION_BLUETOOTH, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_CONEXION_BLUETOOTH_screen_init);
    }
}

void ui_event_ModoJUEGO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MODO_JUEGO, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MODO_JUEGO_screen_init);
    }
}

void ui_event_ModoREHABILITACION(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MODO_REHABILITACION, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MODO_REHABILITACION_screen_init);
    }
}

// build funtions

void ui_SELECCION_DE_MODO_screen_init(void)
{
    ui_SELECCION_DE_MODO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SELECCION_DE_MODO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SELECCION_DE_MODO1 = lv_img_create(ui_SELECCION_DE_MODO);
    lv_img_set_src(ui_SELECCION_DE_MODO1, &ui_img_3_png);
    lv_obj_set_width(ui_SELECCION_DE_MODO1, 480);
    lv_obj_set_height(ui_SELECCION_DE_MODO1, 320);
    lv_obj_set_align(ui_SELECCION_DE_MODO1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SELECCION_DE_MODO1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SELECCION_DE_MODO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME3 = lv_btn_create(ui_SELECCION_DE_MODO);
    lv_obj_set_width(ui_HOME3, 41);
    lv_obj_set_height(ui_HOME3, 44);
    lv_obj_set_x(ui_HOME3, 217);
    lv_obj_set_y(ui_HOME3, -135);
    lv_obj_set_align(ui_HOME3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH3 = lv_btn_create(ui_SELECCION_DE_MODO);
    lv_obj_set_width(ui_BLUETOOTH3, 26);
    lv_obj_set_height(ui_BLUETOOTH3, 43);
    lv_obj_set_x(ui_BLUETOOTH3, 177);
    lv_obj_set_y(ui_BLUETOOTH3, -137);
    lv_obj_set_align(ui_BLUETOOTH3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLUETOOTH3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLUETOOTH3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBAR3 = lv_bar_create(ui_SELECCION_DE_MODO);
    lv_bar_set_value(ui_BatteryBAR3, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBAR3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBAR3, 51);
    lv_obj_set_height(ui_BatteryBAR3, 22);
    lv_obj_set_x(ui_BatteryBAR3, -199);
    lv_obj_set_y(ui_BatteryBAR3, -140);
    lv_obj_set_align(ui_BatteryBAR3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBAR3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteryBAR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBAR3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBAR3, lv_color_hex(0x5AEEFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBAR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblBatteryTxt3 = lv_label_create(ui_SELECCION_DE_MODO);
    lv_obj_set_width(ui_lblBatteryTxt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBatteryTxt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBatteryTxt3, -198);
    lv_obj_set_y(ui_lblBatteryTxt3, -140);
    lv_obj_set_align(ui_lblBatteryTxt3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblBatteryTxt3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatteryTxt3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatteryTxt3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatteryTxt3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatteryTxt3, lv_color_hex(0x54EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatteryTxt3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModoJUEGO = lv_btn_create(ui_SELECCION_DE_MODO);
    lv_obj_set_width(ui_ModoJUEGO, 182);
    lv_obj_set_height(ui_ModoJUEGO, 163);
    lv_obj_set_x(ui_ModoJUEGO, -99);
    lv_obj_set_y(ui_ModoJUEGO, 59);
    lv_obj_set_align(ui_ModoJUEGO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModoJUEGO, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ModoJUEGO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ModoJUEGO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModoJUEGO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModoREHABILITACION = lv_btn_create(ui_SELECCION_DE_MODO);
    lv_obj_set_width(ui_ModoREHABILITACION, 182);
    lv_obj_set_height(ui_ModoREHABILITACION, 163);
    lv_obj_set_x(ui_ModoREHABILITACION, 109);
    lv_obj_set_y(ui_ModoREHABILITACION, 59);
    lv_obj_set_align(ui_ModoREHABILITACION, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModoREHABILITACION, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ModoREHABILITACION, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ModoREHABILITACION, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModoREHABILITACION, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HOME3, ui_event_HOME3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLUETOOTH3, ui_event_BLUETOOTH3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModoJUEGO, ui_event_ModoJUEGO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModoREHABILITACION, ui_event_ModoREHABILITACION, LV_EVENT_ALL, NULL);

}

void ui_SELECCION_DE_MODO_screen_destroy(void)
{
    if(ui_SELECCION_DE_MODO) lv_obj_del(ui_SELECCION_DE_MODO);

    // NULL screen variables
    ui_SELECCION_DE_MODO = NULL;
    ui_SELECCION_DE_MODO1 = NULL;
    ui_HOME3 = NULL;
    ui_BLUETOOTH3 = NULL;
    ui_BatteryBAR3 = NULL;
    ui_lblBatteryTxt3 = NULL;
    ui_ModoJUEGO = NULL;
    ui_ModoREHABILITACION = NULL;

}
